version: 0.2

phases:
  install:
    commands:
      - echo Installing deps
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run test-ci
  post_build:
    commands:
      - echo Build completed on `date`